spring:
  security:
#    user:
#      name: user
#      password: 1111
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL57Dialect
  hikari:
    jdbc-url: jdbc:h2:mem

  main:
    allow-circular-references: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #db는 스네이트 표기법, dto는 카멜케이스 사용 시



