spring:
  security:
#    user:
#      name: user
#      password: 1111
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password: Dltkdgjs!23
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #        dialect: org.hibernate.dialect.MySQL57Dialect
  hikari:
    jdbc-url: jdbc:h2:mem

  main:
    allow-circular-references: true

  #파일 업로드를 위한 설정
  servlet:
    multipart:
      max-request-size: 30MB #
      max-file-size: 10MB # 한파일의 최대크기

# 업로드 폴더 지정
org:
  mall:
    upload:
      path: upload

# -- 마이바티스 임시 중단
#mybatis:
#  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true #db는 스네이트 표기법, dto는 카멜케이스 사용 시

logging:
  level:
    org:
      springframework:
        security:
          web: trace # 시큐리티에서 로그 설정
      hibernate:
        type:
          descriptor:
            sql: trace # 쿼리의 변수 까지 로깅하기 위함


# 에러 RES JSON에 message, trace 로 메세지 추가
server:
  error:
    include-message: always
#    include-stacktrace: always

springdoc:
  swagger-ui:
    disable-swagger-default-url: true   #디폴트 페이지 안나오게
    path: /api-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json